"""Drift guard for the committed Intel sample report.

`examples/intel_2024_sample_report.txt` is regenerated by
`scripts/generate_public_sample.py` and quoted in the README, but nothing checked
that it still matched the pipeline. It had drifted: it reported
`Overall Risk: 42.7/100 (Moderate)` while the code produced `39.1/100 (Low)`, and
it still used the old `Confidence:` label. A reader of the repository saw a
different risk band than the engine reports.

The headline number later drifted a second way: `Assessment.overall_score` is the
weighted dimension aggregate (39.1/Low) while the decision is derived from the
fusion score (73.0/High), so a report that printed only `overall_score` stated a
band the engine had not decided. The renderer now labels each number separately,
which is why the guarded headline is `Decision-bearing risk score:`.

The PDF is regenerated alongside it but cannot be byte-compared (reportlab stamps
it with the creation time), so this guard covers the text artifact.
"""

from __future__ import annotations

import json
from pathlib import Path

from finrisk.pipeline import FinRiskPipeline
from finrisk.report import render_text_report

ROOT = Path(__file__).resolve().parents[1]
ARTIFACT = ROOT / "examples" / "intel_2024_sample_report.txt"
OBSERVATIONS = ROOT / "research" / "benchmark" / "public_company_observations.json"
HEADLINE = "Decision-bearing risk score:"


def _rendered_report() -> str:
    data = json.loads(OBSERVATIONS.read_text(encoding="utf-8"))
    example = next(x for x in data["examples"] if x["id"] == "intc-2024")
    pipeline = FinRiskPipeline(ROOT)
    assessment = pipeline.assess(
        example["company"],
        example["fiscal_year"],
        example["current"],
        example["previous"],
        {int(key): value for key, value in example["pages"].items()},
        example["filing_url"],
    )
    return render_text_report(assessment, pipeline.decide(assessment))


def test_rendering_the_sample_report_is_deterministic():
    assert _rendered_report() == _rendered_report()


def test_committed_sample_report_matches_the_current_pipeline():
    committed = ARTIFACT.read_text(encoding="utf-8")
    assert committed == _rendered_report(), (
        "examples/intel_2024_sample_report.txt is stale; run "
        "python scripts/generate_public_sample.py"
    )


def test_sample_report_states_the_score_the_engine_produces():
    """The headline number and band are the part a reader actually quotes."""
    committed = ARTIFACT.read_text(encoding="utf-8")
    rendered_report = _rendered_report()
    headline = next(line for line in committed.splitlines() if line.startswith(HEADLINE))
    rendered = next(line for line in rendered_report.splitlines() if line.startswith(HEADLINE))
    assert headline == rendered


def test_sample_report_headline_is_not_the_weighted_aggregate():
    """Guard the reason the headline was relabelled: the two scores differ."""
    rendered = _rendered_report()
    decision_score = next(line for line in rendered.splitlines() if line.startswith(HEADLINE))
    weighted = next(
        line for line in rendered.splitlines() if line.startswith("Weighted dimension score:")
    )
    assert decision_score != weighted
    assert "Decision:" in rendered
