from __future__ import annotations

from enum import StrEnum


class AssuranceReasonCode(StrEnum):
    """Stable, machine-readable explanations emitted by the assurance runtime."""

    INSUFFICIENT_VERIFIED_EVIDENCE = "INSUFFICIENT_VERIFIED_EVIDENCE"
    EVIDENCE_FRAGILITY_HIGH = "EVIDENCE_FRAGILITY_HIGH"
    EVIDENCE_FRAGILITY_NOT_ESTIMABLE = "EVIDENCE_FRAGILITY_NOT_ESTIMABLE"
    OUTSIDE_VALIDATED_DISTRIBUTION = "OUTSIDE_VALIDATED_DISTRIBUTION"
    DISTRIBUTION_VALIDITY_UNKNOWN = "DISTRIBUTION_VALIDITY_UNKNOWN"
    ASSURANCE_POLICY_UNCALIBRATED = "ASSURANCE_POLICY_UNCALIBRATED"
    CALIBRATION_SCOPE_MISMATCH = "CALIBRATION_SCOPE_MISMATCH"
    CERTIFICATE_INCOMPLETE = "CERTIFICATE_INCOMPLETE"
    REPORTING_OBSERVABILITY_ANOMALY = "REPORTING_OBSERVABILITY_ANOMALY"
    HIGH_MODEL_DISAGREEMENT = "HIGH_MODEL_DISAGREEMENT"
    RUNTIME_FAILURE_REQUIRES_REVIEW = "RUNTIME_FAILURE_REQUIRES_REVIEW"
    PROPOSED_DECISION_WITHHELD = "PROPOSED_DECISION_WITHHELD"
