'use client';

import {FormEvent,useState} from 'react';

type Evidence={source:string;document:string;page:number|null;quote:string;confidence:number;verification_status:string};
type Conclusion={claim:string;reason:string;tool:string;rationale:string;confidence:number;evidence:Evidence[]};
type Trace={step_id:string;phase:string;tool:string;status:string;summary:string;error?:string};
type Agent={status:string;confidence:number;evidence_coverage:number;plan:{id:string;phase:string;tool:string;purpose:string}[];trace:Trace[];conclusions:Conclusion[];reflection:string[];warnings:string[]};
type Result={company:string;overall_score:number|null;risk_level:string;confidence:number;dimensions:Record<string,{score:number|null;level:string;key_drivers:string[]}>;metrics:Record<string,{value:number|null;formula:string}>;models:{name:string;output:number|null;interpretation:string;applicability:string}[];contradictions:{category:string;management_claim:string;conflicting_evidence:string[]}[];missing_information:string[];disclaimer:string;agent?:Agent;extraction?:{review_required:boolean}};
const labels:Record<string,string>={liquidity:'Liquidity',solvency_leverage:'Solvency & Leverage',profitability:'Profitability',cash_flow:'Cash Flow',earnings_quality:'Earnings Quality',accounting:'Accounting',governance_audit:'Governance & Audit',business_going_concern:'Business / Going Concern'};

export default function Home(){
  const [file,setFile]=useState<File|null>(null),[company,setCompany]=useState(''),[year,setYear]=useState(new Date().getFullYear()-1),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();if(!file)return;setLoading(true);setError('');const body=new FormData();body.append('company',company);body.append('fiscal_year',String(year));body.append('file',file);try{const res=await fetch('http://localhost:8000/api/v1/documents/analyze',{method:'POST',body});const data=await res.json();if(!res.ok)throw new Error(data.detail||'Analysis failed');setResult(data)}catch(err){setError(err instanceof Error?err.message:'Analysis failed')}finally{setLoading(false)}}
  return <main>
    <header><div><span className="eyebrow">INTERFACE SHOWS · AGENT REASONS · TOOLS EXECUTE · EVIDENCE GROUNDS</span><h1>FinRisk<span>Agent</span></h1></div><div className="status">● Local API</div></header>
    <section className="hero"><div><p className="kicker">Three-layer financial reasoning</p><h2>Every material conclusion has a path back to evidence.</h2><p>Upload an English annual report. The Agent plans and coordinates typed financial tools; unsupported claims are rejected and inadequate coverage produces an abstention.</p><form onSubmit={submit}><input aria-label="Company" placeholder="Company name" value={company} onChange={e=>setCompany(e.target.value)} required/><input aria-label="Fiscal year" type="number" value={year} onChange={e=>setYear(Number(e.target.value))} required/><label className="upload"><input type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><b>{file?.name||'Choose annual report'}</b><small>PDF · maximum 50 MB</small></label><button disabled={!file||loading}>{loading?'Agent is analyzing…':'Run Agent analysis'}</button></form>{error&&<p className="error">{error}</p>}</div>{result&&<aside><span className="agentStatus">{result.agent?.status||'ASSESSMENT'}</span><div className="score">{result.overall_score??'N/A'}<small>{result.overall_score!==null?'/100':''}</small></div><b>{result.risk_level}</b><p>Confidence: {result.confidence}</p><p>Evidence coverage: {result.agent?.evidence_coverage??'N/A'}</p><em>{result.extraction?.review_required?'Extraction review required':'Verified inputs'}</em></aside>}</section>
    {result&&<>
      <section><div className="sectionTitle"><h3>Risk dashboard</h3><p>{result.company}</p></div><div className="grid">{Object.entries(result.dimensions).map(([key,d],i)=><article key={key}><div className="num">0{i+1}</div><h4>{labels[key]||key}</h4><strong>{d.score??'N/A'} {d.level}</strong><div className="bar"><i style={{width:`${d.score??0}%`}}/></div><p>{d.key_drivers.join(', ')||'Insufficient triggered evidence'}</p></article>)}</div></section>
      {result.agent&&<section className="agentPanel"><div className="sectionTitle"><h3>Agent workflow</h3><p>Public structured trace · no hidden chain-of-thought</p></div><div className="timeline">{result.agent.trace.map((t,i)=><div className="trace" key={`${t.step_id}-${i}`}><span>{i+1}</span><div><small>{t.phase}</small><b>{t.tool}</b><p>{t.summary}{t.error&&`: ${t.error}`}</p></div><em>{t.status}</em></div>)}</div>
      <h3>Conclusion → Reason → Tool result → Evidence</h3>{result.agent.conclusions.length?result.agent.conclusions.map((c,i)=><article className="conclusion" key={i}><div className="claim"><small>CONCLUSION</small><h4>{c.claim}</h4><p>{c.reason}</p></div><div><small>TOOL / RATIONALE</small><b>{c.tool}</b><p>{c.rationale} · confidence {c.confidence}</p></div><div><small>VERIFIED EVIDENCE</small>{c.evidence.map((ev,j)=><blockquote key={j}><b>{ev.verification_status}</b> · {ev.document}{ev.page?` · page ${ev.page}`:''}<br/>{ev.quote}</blockquote>)}</div></article>):<p className="notice">No evidence-supported material risk conclusion was admitted.</p>}
      {[...result.agent.reflection,...result.agent.warnings].length>0&&<div className="warnings"><b>Reflection and uncertainty</b><ul>{[...result.agent.reflection,...result.agent.warnings].map((x,i)=><li key={i}>{x}</li>)}</ul></div>}</section>}
      <section className="detailGrid"><div><h3>Quantitative models</h3>{result.models.map(m=><article className="compact" key={m.name}><b>{m.name}</b><span>{m.output??'N/A'}</span><p>{m.interpretation} · {m.applicability}</p></article>)}</div><div><h3>Contradictions</h3>{result.contradictions.length?result.contradictions.map((c,i)=><article className="compact" key={i}><b>{c.category}</b><p>{c.management_claim}</p><ul>{c.conflicting_evidence.map((x,j)=><li key={j}>{x}</li>)}</ul></article>):<p className="notice">No verified narrative–numeric contradiction detected.</p>}</div></section>
    </>}
    <footer>{result?.disclaimer||'Risk scores are heuristic assessments, not bankruptcy probabilities or investment advice.'}</footer>
  </main>
}
