"""Regenerate ``frontend/lib/demoFixture.ts`` from the current pipeline.

The Workbench ships a bundled offline sample so a reviewer can see the whole UI
without a backend. That sample is a real pipeline output, so it has to be
regenerated whenever the pipeline's output changes -- otherwise the offline demo
drifts away from the engine (it once showed a REVIEW where the engine now
returns ABSTAIN, and one of its decision paths crashed the Decision paths tab).

The projection key set is derived from ``AssessmentPayload`` in
``frontend/lib/types.ts`` rather than hard-coded, so the artifact can never
silently drop or invent a declared field.

Usage:
    python scripts/generate_demo_fixture.py            # write the file
    python scripts/generate_demo_fixture.py --check    # fail if it is stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

TARGET = ROOT / "frontend" / "lib" / "demoFixture.ts"
TYPES = ROOT / "frontend" / "lib" / "types.ts"
SOURCE_FIXTURE = "examples/synthetic_company.json"
SOURCE_FILING = "research/results/public_v1/summary.json"
GENERATED_BY = "FinancialRiskAgent v0.3.3 (deterministic offline provider)"
NOTICE = (
    "Bundled offline sample. The assessment is a real pipeline output for the "
    "repository's synthetic fixture - not a real issuer, and not a live run. "
    "Reliability is UNCALIBRATED."
)

HEADER = """// AUTO-GENERATED by scripts/generate_demo_fixture.py. Do not edit by hand.
// Real pipeline output for the repository's synthetic fixture; used when the
// API upstream is unreachable so the Workbench is never an empty shell.
import type { PilotPayload, AssessmentPayload } from './types';

export interface DemoFixture {
  generatedBy: string;
  sourceFixture: string;
  sourceFiling: string;
  notice: string;
  pilot: PilotPayload;
  assessment: AssessmentPayload;
}

export const DEMO_FIXTURE: DemoFixture = """


def declared_assessment_keys() -> tuple[list[str], set[str]]:
    """Read the declared keys of `AssessmentPayload`, and which are optional."""
    text = TYPES.read_text(encoding="utf-8")
    start = text.index("export interface AssessmentPayload {")
    body = text[start: text.index("\n}", start)]
    keys: list[str] = []
    optional: set[str] = set()
    for match in re.finditer(r"^\s*(\w+)(\??):", body, re.MULTILINE):
        keys.append(match.group(1))
        if match.group(2):
            optional.add(match.group(1))
    if not keys:
        raise SystemExit("could not read AssessmentPayload keys from types.ts")
    return keys, optional


def build_assessment() -> dict:
    from finrisk.agent import FinancialRiskAgent
    from finrisk.api import document_response

    data = json.loads((ROOT / SOURCE_FIXTURE).read_text(encoding="utf-8"))
    state = FinancialRiskAgent(ROOT).run(
        data["company"],
        data["fiscal_year"],
        data["current"],
        data["previous"],
        {int(key): value for key, value in data["pages"].items()},
    )
    payload = document_response(state)

    keys, optional = declared_assessment_keys()
    missing = [key for key in keys if key not in payload and key not in optional]
    if missing:
        raise SystemExit(
            f"AssessmentPayload declares {missing} but the pipeline no longer emits them"
        )
    return {key: payload[key] for key in sorted(keys) if key in payload}


def build_pilot() -> dict:
    """The frozen pilot payload, taken through the real endpoint."""
    from fastapi.testclient import TestClient
    from finrisk.api import app

    with TestClient(app) as client:
        response = client.get("/api/v1/public-pilot")
        response.raise_for_status()
        return response.json()


def render() -> str:
    fixture = {
        "generatedBy": GENERATED_BY,
        "sourceFixture": SOURCE_FIXTURE,
        "sourceFiling": SOURCE_FILING,
        "notice": NOTICE,
        "pilot": build_pilot(),
        "assessment": build_assessment(),
    }
    body = json.dumps(fixture, indent=2, ensure_ascii=False)
    return f"{HEADER}{body} as DemoFixture;\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero when the committed artifact differs (ignores wall-clock fields)",
    )
    args = parser.parse_args(argv[1:])

    generated = render()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if comparable(generated) != comparable(current):
            print("frontend/lib/demoFixture.ts is stale; run scripts/generate_demo_fixture.py")
            return 1
        print("frontend/lib/demoFixture.ts is up to date")
        return 0

    TARGET.write_text(generated, encoding="utf-8", newline="\n")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


VOLATILE = ("latency_ms",)


def comparable(text: str) -> str:
    """Strip wall-clock fields so two runs of the same pipeline compare equal."""
    try:
        body = text[text.index("= {") + 2 : text.rindex("} as DemoFixture;") + 1]
        data = json.loads(body)
    except (ValueError, json.JSONDecodeError):
        return text

    def scrub(value):
        if isinstance(value, dict):
            return {k: ("<wall-clock>" if k in VOLATILE else scrub(v)) for k, v in value.items()}
        if isinstance(value, list):
            return [scrub(item) for item in value]
        return value

    return json.dumps(scrub(data), sort_keys=True)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
