// AUTO-GENERATED by scripts/generate_demo_fixture.py. Do not edit by hand.
// Real pipeline output for the repository's synthetic fixture; used when the
// API upstream is unreachable so the Workbench is never an empty shell.
import type { PilotPayload, AssessmentPayload } from './types';

export interface DemoFixture {
  generatedBy: string;
  sourceFixture: string;
  sourceFiling: string;
  notice: string;
  pilot: PilotPayload;
  assessment: AssessmentPayload;
}

export const DEMO_FIXTURE: DemoFixture = {
  "generatedBy": "FinancialRiskAgent v0.3.2 (deterministic offline provider)",
  "sourceFixture": "examples/synthetic_company.json",
  "sourceFiling": "research/results/public_v1/summary.json",
  "notice": "Bundled offline sample. The assessment is a real pipeline output for the repository's synthetic fixture - not a real issuer, and not a live run. Reliability is UNCALIBRATED.",
  "pilot": {
    "snapshot": "v0.3.0 frozen public pilot",
    "runtime": "v0.3.2",
    "annotation_status": "single-reviewer pilot; not a definitive financial-risk benchmark",
    "benchmark_evidence_coverage": 0.5833,
    "rows": [
      {
        "entity": "Apple Inc.",
        "decision": "PASS",
        "score": null,
        "reliability": "UNCALIBRATED",
        "filing": "aapl-2024"
      },
      {
        "entity": "Microsoft Corporation",
        "decision": "PASS",
        "score": 24.0,
        "reliability": "UNCALIBRATED",
        "filing": "msft-2024"
      },
      {
        "entity": "Intel Corporation",
        "decision": "PASS",
        "score": 42.7,
        "reliability": "UNCALIBRATED",
        "filing": "intc-2024"
      }
    ]
  },
  "assessment": {
    "agent": {
      "status": "REVIEW_REQUIRED",
      "plan": [
        {
          "id": "metrics",
          "phase": "analyze",
          "tool": "financial_metrics",
          "purpose": "Calculate ratios and trends deterministically"
        },
        {
          "id": "models",
          "phase": "analyze",
          "tool": "traditional_models",
          "purpose": "Evaluate model applicability and outputs"
        },
        {
          "id": "claims",
          "phase": "collect",
          "tool": "narrative_evidence",
          "purpose": "Extract and verify narrative claims"
        },
        {
          "id": "rules",
          "phase": "analyze",
          "tool": "risk_rules",
          "purpose": "Evaluate configured expert risk signals"
        },
        {
          "id": "consistency",
          "phase": "cross_check",
          "tool": "contradiction_detection",
          "purpose": "Compare verified claims with numeric facts"
        },
        {
          "id": "periods",
          "phase": "cross_check",
          "tool": "period_comparison",
          "purpose": "Confirm multi-period coverage"
        },
        {
          "id": "assessment",
          "phase": "synthesize",
          "tool": "risk_assessment",
          "purpose": "Create deterministic evidence-linked assessment"
        },
        {
          "id": "verification",
          "phase": "verify",
          "tool": "claim_verification",
          "purpose": "Reject unsupported material conclusions"
        }
      ],
      "trace": [
        {
          "step_id": "metrics",
          "phase": "analyze",
          "tool": "financial_metrics",
          "status": "success",
          "summary": "Produced 30 structured result(s)",
          "evidence_ids": [],
          "error": null,
          "latency_ms": 0
        },
        {
          "step_id": "models",
          "phase": "analyze",
          "tool": "traditional_models",
          "status": "success",
          "summary": "Produced 4 structured result(s)",
          "evidence_ids": [],
          "error": null,
          "latency_ms": 0
        },
        {
          "step_id": "claims",
          "phase": "collect",
          "tool": "narrative_evidence",
          "status": "success",
          "summary": "Produced 2 structured result(s)",
          "evidence_ids": [],
          "error": null,
          "latency_ms": 0
        },
        {
          "step_id": "rules",
          "phase": "analyze",
          "tool": "risk_rules",
          "status": "success",
          "summary": "Produced 21 structured result(s)",
          "evidence_ids": [],
          "error": null,
          "latency_ms": 0
        },
        {
          "step_id": "consistency",
          "phase": "cross_check",
          "tool": "contradiction_detection",
          "status": "success",
          "summary": "Produced 1 structured result(s)",
          "evidence_ids": [],
          "error": null,
          "latency_ms": 0
        },
        {
          "step_id": "periods",
          "phase": "cross_check",
          "tool": "period_comparison",
          "status": "success",
          "summary": "Produced 2 structured result(s)",
          "evidence_ids": [],
          "error": null,
          "latency_ms": 0
        },
        {
          "step_id": "assessment",
          "phase": "synthesize",
          "tool": "risk_assessment",
          "status": "success",
          "summary": "Produced 1 structured result(s)",
          "evidence_ids": [],
          "error": null,
          "latency_ms": 0
        },
        {
          "step_id": "verification",
          "phase": "verify",
          "tool": "claim_verification",
          "status": "success",
          "summary": "Produced 2 structured result(s)",
          "evidence_ids": [],
          "error": null,
          "latency_ms": 0
        }
      ],
      "conclusions": [
        {
          "claim": "liquidity risk signal LIQ_001",
          "reason": "Current assets do not cover current liabilities.",
          "tool": "risk_rules",
          "rationale": "Configured rule LIQ_001 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "current_ratio=0.8282828282828283 < 1.0",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "liquidity risk signal LIQ_002",
          "reason": "Liquidity cushion is thin.",
          "tool": "risk_rules",
          "rationale": "Configured rule LIQ_002 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "current_ratio=0.8282828282828283 < 1.25",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "liquidity risk signal LIQ_003",
          "reason": "Liquid assets provide weak short-term coverage.",
          "tool": "risk_rules",
          "rationale": "Configured rule LIQ_003 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "quick_ratio=0.5454545454545454 < 0.75",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "liquidity risk signal LIQ_004",
          "reason": "Immediate cash coverage is limited.",
          "tool": "risk_rules",
          "rationale": "Configured rule LIQ_004 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "cash_ratio=0.08484848484848485 < 0.15",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "liquidity risk signal LIQ_005",
          "reason": "Negative working capital increases short-term funding pressure.",
          "tool": "risk_rules",
          "rationale": "Configured rule LIQ_005 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "working_capital=-85 < 0",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "liquidity risk signal LIQ_006",
          "reason": "Cash declined materially year over year.",
          "tool": "risk_rules",
          "rationale": "Configured rule LIQ_006 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "cash_growth=-0.373134328358209 < -0.2",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "liquidity risk signal LIQ_007",
          "reason": "Deteriorating liquidity combines with rising refinancing pressure.",
          "tool": "risk_rules",
          "rationale": "Configured rule LIQ_007 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "current_ratio=0.8282828282828283 < 1.0",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            },
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "short_term_debt_growth=0.7272727272727273 > 0.2",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            },
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "cash_growth=-0.373134328358209 < 0",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "liquidity risk signal LIQ_008",
          "reason": "Both cash reserves and operating cash generation weakened.",
          "tool": "risk_rules",
          "rationale": "Configured rule LIQ_008 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "cash_growth=-0.373134328358209 < -0.25",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            },
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "operating_cash_flow_growth=-0.6538461538461539 < -0.2",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "solvency_leverage risk signal SOL_001",
          "reason": "Debt is high relative to book equity.",
          "tool": "risk_rules",
          "rationale": "Configured rule SOL_001 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "debt_to_equity=2.0689655172413794 > 2.0",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "solvency_leverage risk signal SOL_004",
          "reason": "Operating earnings weakly cover interest expense.",
          "tool": "risk_rules",
          "rationale": "Configured rule SOL_004 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "interest_coverage=1.2363636363636363 < 1.5",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "solvency_leverage risk signal SOL_005",
          "reason": "Interest coverage has limited headroom.",
          "tool": "risk_rules",
          "rationale": "Configured rule SOL_005 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "interest_coverage=1.2363636363636363 < 3.0",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "solvency_leverage risk signal SOL_006",
          "reason": "Debt burden is high relative to EBITDA.",
          "tool": "risk_rules",
          "rationale": "Configured rule SOL_006 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "debt_to_ebitda=5.217391304347826 > 5.0",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "profitability risk signal PRO_003",
          "reason": "Gross margin contracted materially.",
          "tool": "risk_rules",
          "rationale": "Configured rule PRO_003 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "gross_margin_change=-0.03037037037037038 < -0.03",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "cash_flow risk signal CFL_002",
          "reason": "Free cash flow is negative.",
          "tool": "risk_rules",
          "rationale": "Configured rule CFL_002 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "free_cash_flow=-57 < 0",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "cash_flow risk signal CFL_004",
          "reason": "Operating cash flow declined rapidly.",
          "tool": "risk_rules",
          "rationale": "Configured rule CFL_004 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "operating_cash_flow_growth=-0.6538461538461539 < -0.25",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "cash_flow risk signal CFL_005",
          "reason": "Positive earnings have not converted into free cash flow.",
          "tool": "risk_rules",
          "rationale": "Configured rule CFL_005 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "net_income=32 > 0",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            },
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "free_cash_flow=-57 < 0",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "cash_flow risk signal CFL_007",
          "reason": "Cash conversion from reported earnings is weak.",
          "tool": "risk_rules",
          "rationale": "Configured rule CFL_007 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "cfo_to_net_income=0.5625 < 0.8",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "earnings_quality risk signal EQ_001",
          "reason": "Revenue and earnings rose while operating cash flow fell.",
          "tool": "risk_rules",
          "rationale": "Configured rule EQ_001 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "revenue_growth=0.08 > 0",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            },
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "net_income_growth=0.14285714285714285 > 0",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            },
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "operating_cash_flow_growth=-0.6538461538461539 < 0",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "earnings_quality risk signal EQ_002",
          "reason": "Receivables growth substantially outpaces revenue growth.",
          "tool": "risk_rules",
          "rationale": "Configured rule EQ_002 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "accounts_receivable_growth=0.44 > 0.25",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            },
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "revenue_growth=0.08 < 0.1",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "earnings_quality risk signal EQ_003",
          "reason": "Inventory growth outpaces sales and may indicate slowing demand.",
          "tool": "risk_rules",
          "rationale": "Configured rule EQ_003 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "inventory_growth=0.3333333333333333 > 0.25",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            },
            {
              "source": "deterministic",
              "document": "calculated metrics",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": null,
              "quote": "revenue_growth=0.08 < 0.1",
              "value": null,
              "unit": null,
              "confidence": 1.0,
              "verification_status": "derived"
            }
          ]
        },
        {
          "claim": "business_going_concern risk signal BUS_003",
          "reason": "Operations depend materially on successful refinancing.",
          "tool": "risk_rules",
          "rationale": "Configured rule BUS_003 triggered",
          "confidence": 0.9,
          "evidence": [
            {
              "source": "Annual Report",
              "document": "Annual Report",
              "company": "Northstar Components (Synthetic)",
              "period": "2025",
              "page": 54,
              "quote": "The company may pursue refinancing during the coming year",
              "value": null,
              "unit": null,
              "confidence": 0.9,
              "verification_status": "verified"
            }
          ]
        }
      ],
      "warnings": [],
      "reflection": [
        "Narrative and numeric signals conflict; human review is required.",
        "Missing inputs reduce evidence coverage; missing values were not treated as zero."
      ],
      "risk_score": 95.0,
      "confidence": 0.9,
      "confidence_semantics": "LEGACY_EVIDENCE_QUALITY_INDEX_NOT_PROBABILITY",
      "evidence_coverage": 0.045,
      "risk_severity": "critical",
      "risk_trajectory": "insufficient_history",
      "decision": "ABSTAIN",
      "model_disagreement": 0.435,
      "fusion": {
        "method": "hierarchical_escalation",
        "severity": "critical",
        "score": 95.0,
        "decision": "ABSTAIN",
        "evidence_coverage": 0.045,
        "decision_confidence": 0.9,
        "disagreement": 0.435,
        "drivers": [
          "liquidity"
        ],
        "rationale": "Coverage-aware non-compensatory fusion; the highest supported dimension is a monotonic floor and missing dimensions are excluded",
        "evidence_quality": 0.9,
        "reliability": null,
        "reliability_status": "UNCALIBRATED",
        "reason_codes": [
          "INSUFFICIENT_EVIDENCE",
          "CRITICAL_DIMENSION_ESCALATION",
          "UNVALIDATED_RELIABILITY"
        ]
      },
      "decision_trace": {
        "decision": "ABSTAIN",
        "decision_reason_codes": [
          "INSUFFICIENT_EVIDENCE",
          "CRITICAL_DIMENSION_ESCALATION",
          "UNVALIDATED_RELIABILITY"
        ],
        "paths": [
          {
            "reason_code": "LIQ_001",
            "risk_domain": "liquidity",
            "source_evidence": [],
            "required_inputs": [
              "current_ratio"
            ],
            "input_provenance": {
              "current_ratio": []
            },
            "rule_or_model": "liquidity_coverage",
            "rule_version": "64a92069682b8af5042bf05fb1d04be09c3d39b37dfbd6fd9ececf0c8a58d7bc",
            "fusion_version": "hierarchical_escalation:9776c631a261",
            "confidence": 0.9,
            "coverage": 1.0,
            "disagreement": 0.435,
            "fusion_contribution": {
              "method": "hierarchical_escalation",
              "dimension_score": 85,
              "role": "escalator"
            },
            "evidence_path_status": "UNVERIFIED",
            "path": [
              "document",
              "evidence_span",
              "fact",
              "metric",
              "rule/model",
              "dimension",
              "fusion",
              "decision"
            ]
          },
          {
            "reason_code": "LIQ_003",
            "risk_domain": "liquidity",
            "source_evidence": [],
            "required_inputs": [
              "quick_ratio"
            ],
            "input_provenance": {
              "quick_ratio": []
            },
            "rule_or_model": "LIQ_003",
            "rule_version": "64a92069682b8af5042bf05fb1d04be09c3d39b37dfbd6fd9ececf0c8a58d7bc",
            "fusion_version": "hierarchical_escalation:9776c631a261",
            "confidence": 0.9,
            "coverage": 1.0,
            "disagreement": 0.435,
            "fusion_contribution": {
              "method": "hierarchical_escalation",
              "dimension_score": 85,
              "role": "escalator"
            },
            "evidence_path_status": "UNVERIFIED",
            "path": [
              "document",
              "evidence_span",
              "fact",
              "metric",
              "rule/model",
              "dimension",
              "fusion",
              "decision"
            ]
          },
          {
            "reason_code": "LIQ_004",
            "risk_domain": "liquidity",
            "source_evidence": [],
            "required_inputs": [
              "cash_ratio"
            ],
            "input_provenance": {
              "cash_ratio": []
            },
            "rule_or_model": "LIQ_004",
            "rule_version": "64a92069682b8af5042bf05fb1d04be09c3d39b37dfbd6fd9ececf0c8a58d7bc",
            "fusion_version": "hierarchical_escalation:9776c631a261",
            "confidence": 0.9,
            "coverage": 1.0,
            "disagreement": 0.435,
            "fusion_contribution": {
              "method": "hierarchical_escalation",
              "dimension_score": 85,
              "role": "escalator"
            },
            "evidence_path_status": "UNVERIFIED",
            "path": [
              "document",
              "evidence_span",
              "fact",
              "metric",
              "rule/model",
              "dimension",
              "fusion",
              "decision"
            ]
          },
          {
            "reason_code": "LIQ_006",
            "risk_domain": "liquidity",
            "source_evidence": [],
            "required_inputs": [
              "cash_growth"
            ],
            "input_provenance": {
              "cash_growth": []
            },
            "rule_or_model": "LIQ_006",
            "rule_version": "64a92069682b8af5042bf05fb1d04be09c3d39b37dfbd6fd9ececf0c8a58d7bc",
            "fusion_version": "hierarchical_escalation:9776c631a261",
            "confidence": 0.9,
            "coverage": 1.0,
            "disagreement": 0.435,
            "fusion_contribution": {
              "method": "hierarchical_escalation",
              "dimension_score": 85,
              "role": "escalator"
            },
            "evidence_path_status": "UNVERIFIED",
            "path": [
              "document",
              "evidence_span",
              "fact",
              "metric",
              "rule/model",
              "dimension",
              "fusion",
              "decision"
            ]
          },
          {
            "reason_code": "LIQ_008",
            "risk_domain": "liquidity",
            "source_evidence": [],
            "required_inputs": [
              "cash_growth",
              "operating_cash_flow_growth"
            ],
            "input_provenance": {
              "cash_growth": [],
              "operating_cash_flow_growth": []
            },
            "rule_or_model": "LIQ_008",
            "rule_version": "64a92069682b8af5042bf05fb1d04be09c3d39b37dfbd6fd9ececf0c8a58d7bc",
            "fusion_version": "hierarchical_escalation:9776c631a261",
            "confidence": 0.9,
            "coverage": 1.0,
            "disagreement": 0.435,
            "fusion_contribution": {
              "method": "hierarchical_escalation",
              "dimension_score": 85,
              "role": "escalator"
            },
            "evidence_path_status": "UNVERIFIED",
            "path": [
              "document",
              "evidence_span",
              "fact",
              "metric",
              "rule/model",
              "dimension",
              "fusion",
              "decision"
            ]
          },
          {
            "reason_code": "SOL_004",
            "risk_domain": "solvency_leverage",
            "source_evidence": [],
            "required_inputs": [
              "interest_coverage"
            ],
            "input_provenance": {
              "interest_coverage": []
            },
            "rule_or_model": "interest_coverage",
            "rule_version": "64a92069682b8af5042bf05fb1d04be09c3d39b37dfbd6fd9ececf0c8a58d7bc",
            "fusion_version": "hierarchical_escalation:9776c631a261",
            "confidence": 0.9,
            "coverage": 1.0,
            "disagreement": 0.435,
            "fusion_contribution": {
              "method": "hierarchical_escalation",
              "dimension_score": 63,
              "role": "supporting"
            },
            "evidence_path_status": "UNVERIFIED",
            "path": [
              "document",
              "evidence_span",
              "fact",
              "metric",
              "rule/model",
              "dimension",
              "fusion",
              "decision"
            ]
          },
          {
            "reason_code": "SOL_001",
            "risk_domain": "solvency_leverage",
            "source_evidence": [],
            "required_inputs": [
              "debt_to_equity"
            ],
            "input_provenance": {
              "debt_to_equity": []
            },
            "rule_or_model": "SOL_001",
            "rule_version": "64a92069682b8af5042bf05fb1d04be09c3d39b37dfbd6fd9ececf0c8a58d7bc",
            "fusion_version": "hierarchical_escalation:9776c631a261",
            "confidence": 0.9,
            "coverage": 1.0,
            "disagreement": 0.435,
            "fusion_contribution": {
              "method": "hierarchical_escalation",
              "dimension_score": 63,
              "role": "supporting"
            },
            "evidence_path_status": "UNVERIFIED",
            "path": [
              "document",
              "evidence_span",
              "fact",
              "metric",
              "rule/model",
              "dimension",
              "fusion",
              "decision"
            ]
          },
          {
            "reason_code": "SOL_006",
            "risk_domain": "solvency_leverage",
            "source_evidence": [],
            "required_inputs": [
              "debt_to_ebitda"
            ],
            "input_provenance": {
              "debt_to_ebitda": []
            },
            "rule_or_model": "SOL_006",
            "rule_version": "64a92069682b8af5042bf05fb1d04be09c3d39b37dfbd6fd9ececf0c8a58d7bc",
            "fusion_version": "hierarchical_escalation:9776c631a261",
            "confidence": 0.9,
            "coverage": 1.0,
            "disagreement": 0.435,
            "fusion_contribution": {
              "method": "hierarchical_escalation",
              "dimension_score": 63,
              "role": "supporting"
            },
            "evidence_path_status": "UNVERIFIED",
            "path": [
              "document",
              "evidence_span",
              "fact",
              "metric",
              "rule/model",
              "dimension",
              "fusion",
              "decision"
            ]
          },
          {
            "reason_code": "PRO_003",
            "risk_domain": "profitability",
            "source_evidence": [],
            "required_inputs": [
              "gross_margin_change"
            ],
            "input_provenance": {
              "gross_margin_change": []
            },
            "rule_or_model": "PRO_003",
            "rule_version": "64a92069682b8af5042bf05fb1d04be09c3d39b37dfbd6fd9ececf0c8a58d7bc",
            "fusion_version": "hierarchical_escalation:9776c631a261",
            "confidence": 0.9,
            "coverage": 1.0,
            "disagreement": 0.435,
            "fusion_contribution": {
              "method": "hierarchical_escalation",
              "dimension_score": 20,
              "role": "supporting"
            },
            "evidence_path_status": "UNVERIFIED",
            "path": [
              "document",
              "evidence_span",
              "fact",
              "metric",
              "rule/model",
              "dimension",
              "fusion",
              "decision"
            ]
          },
          {
            "reason_code": "CFL_005",
            "risk_domain": "cash_flow",
            "source_evidence": [],
            "required_inputs": [
              "net_income",
              "free_cash_flow"
            ],
            "input_provenance": {
              "net_income": [],
              "free_cash_flow": []
            },
            "rule_or_model": "cash_deficit",
            "rule_version": "64a92069682b8af5042bf05fb1d04be09c3d39b37dfbd6fd9ececf0c8a58d7bc",
            "fusion_version": "hierarchical_escalation:9776c631a261",
            "confidence": 0.9,
            "coverage": 1.0,
            "disagreement": 0.435,
            "fusion_contribution": {
              "method": "hierarchical_escalation",
              "dimension_score": 45,
              "role": "supporting"
            },
            "evidence_path_status": "UNVERIFIED",
            "path": [
              "document",
              "evidence_span",
              "fact",
              "metric",
              "rule/model",
              "dimension",
              "fusion",
              "decision"
            ]
          },
          {
            "reason_code": "CFL_004",
            "risk_domain": "cash_flow",
            "source_evidence": [],
            "required_inputs": [
              "operating_cash_flow_growth"
            ],
            "input_provenance": {
              "operating_cash_flow_growth": []
            },
            "rule_or_model": "CFL_004",
            "rule_version": "64a92069682b8af5042bf05fb1d04be09c3d39b37dfbd6fd9ececf0c8a58d7bc",
            "fusion_version": "hierarchical_escalation:9776c631a261",
            "confidence": 0.9,
            "coverage": 1.0,
            "disagreement": 0.435,
            "fusion_contribution": {
              "method": "hierarchical_escalation",
              "dimension_score": 45,
              "role": "supporting"
            },
            "evidence_path_status": "UNVERIFIED",
            "path": [
              "document",
              "evidence_span",
              "fact",
              "metric",
              "rule/model",
              "dimension",
              "fusion",
              "decision"
            ]
          },
          {
            "reason_code": "CFL_007",
            "risk_domain": "cash_flow",
            "source_evidence": [],
            "required_inputs": [
              "cfo_to_net_income"
            ],
            "input_provenance": {
              "cfo_to_net_income": []
            },
            "rule_or_model": "CFL_007",
            "rule_version": "64a92069682b8af5042bf05fb1d04be09c3d39b37dfbd6fd9ececf0c8a58d7bc",
            "fusion_version": "hierarchical_escalation:9776c631a261",
            "confidence": 0.9,
            "coverage": 1.0,
            "disagreement": 0.435,
            "fusion_contribution": {
              "method": "hierarchical_escalation",
              "dimension_score": 45,
              "role": "supporting"
            },
            "evidence_path_status": "UNVERIFIED",
            "path": [
              "document",
              "evidence_span",
              "fact",
              "metric",
              "rule/model",
              "dimension",
              "fusion",
              "decision"
            ]
          },
          {
            "reason_code": "EQ_001",
            "risk_domain": "earnings_quality",
            "source_evidence": [],
            "required_inputs": [
              "revenue_growth",
              "net_income_growth",
              "operating_cash_flow_growth"
            ],
            "input_provenance": {
              "revenue_growth": [],
              "net_income_growth": [],
              "operating_cash_flow_growth": []
            },
            "rule_or_model": "EQ_001",
            "rule_version": "64a92069682b8af5042bf05fb1d04be09c3d39b37dfbd6fd9ececf0c8a58d7bc",
            "fusion_version": "hierarchical_escalation:9776c631a261",
            "confidence": 0.9,
            "coverage": 1.0,
            "disagreement": 0.435,
            "fusion_contribution": {
              "method": "hierarchical_escalation",
              "dimension_score": 56,
              "role": "supporting"
            },
            "evidence_path_status": "UNVERIFIED",
            "path": [
              "document",
              "evidence_span",
              "fact",
              "metric",
              "rule/model",
              "dimension",
              "fusion",
              "decision"
            ]
          },
          {
            "reason_code": "EQ_002",
            "risk_domain": "earnings_quality",
            "source_evidence": [],
            "required_inputs": [
              "accounts_receivable_growth",
              "revenue_growth"
            ],
            "input_provenance": {
              "accounts_receivable_growth": [],
              "revenue_growth": []
            },
            "rule_or_model": "EQ_002",
            "rule_version": "64a92069682b8af5042bf05fb1d04be09c3d39b37dfbd6fd9ececf0c8a58d7bc",
            "fusion_version": "hierarchical_escalation:9776c631a261",
            "confidence": 0.9,
            "coverage": 1.0,
            "disagreement": 0.435,
            "fusion_contribution": {
              "method": "hierarchical_escalation",
              "dimension_score": 56,
              "role": "supporting"
            },
            "evidence_path_status": "UNVERIFIED",
            "path": [
              "document",
              "evidence_span",
              "fact",
              "metric",
              "rule/model",
              "dimension",
              "fusion",
              "decision"
            ]
          },
          {
            "reason_code": "EQ_003",
            "risk_domain": "earnings_quality",
            "source_evidence": [],
            "required_inputs": [
              "inventory_growth",
              "revenue_growth"
            ],
            "input_provenance": {
              "inventory_growth": [],
              "revenue_growth": []
            },
            "rule_or_model": "EQ_003",
            "rule_version": "64a92069682b8af5042bf05fb1d04be09c3d39b37dfbd6fd9ececf0c8a58d7bc",
            "fusion_version": "hierarchical_escalation:9776c631a261",
            "confidence": 0.9,
            "coverage": 1.0,
            "disagreement": 0.435,
            "fusion_contribution": {
              "method": "hierarchical_escalation",
              "dimension_score": 56,
              "role": "supporting"
            },
            "evidence_path_status": "UNVERIFIED",
            "path": [
              "document",
              "evidence_span",
              "fact",
              "metric",
              "rule/model",
              "dimension",
              "fusion",
              "decision"
            ]
          },
          {
            "reason_code": "BUS_003",
            "risk_domain": "business_going_concern",
            "source_evidence": [
              {
                "document": "Annual Report",
                "page": 54,
                "source_text": "The company may pursue refinancing during the coming year",
                "fiscal_year": 2025,
                "confidence": 0.9,
                "verified": true,
                "verification_status": "verified",
                "source": "Annual Report",
                "company": null,
                "period": "2025",
                "quote": "The company may pursue refinancing during the coming year",
                "value": null,
                "unit": null
              }
            ],
            "required_inputs": [
              "refinancing_dependency"
            ],
            "input_provenance": {
              "refinancing_dependency": [
                {
                  "document": "Annual Report",
                  "page": 54,
                  "source_text": "The company may pursue refinancing during the coming year",
                  "fiscal_year": 2025,
                  "confidence": 0.9,
                  "verified": true,
                  "verification_status": "verified",
                  "source": "Annual Report",
                  "company": null,
                  "period": "2025",
                  "quote": "The company may pursue refinancing during the coming year",
                  "value": null,
                  "unit": null
                }
              ]
            },
            "rule_or_model": "BUS_003",
            "rule_version": "64a92069682b8af5042bf05fb1d04be09c3d39b37dfbd6fd9ececf0c8a58d7bc",
            "fusion_version": "hierarchical_escalation:9776c631a261",
            "confidence": 0.9,
            "coverage": 1.0,
            "disagreement": 0.435,
            "fusion_contribution": {
              "method": "hierarchical_escalation",
              "dimension_score": 28,
              "role": "supporting"
            },
            "evidence_path_status": "VERIFIED",
            "path": [
              "document",
              "evidence_span",
              "fact",
              "metric",
              "rule/model",
              "dimension",
              "fusion",
              "decision"
            ]
          },
          {
            "reason_code": "DISCLOSURE_TENSION_001",
            "risk_domain": "liquidity",
            "source_evidence": [
              {
                "document": "Annual Report",
                "page": 54,
                "source_text": "Management believes liquidity remains strong",
                "fiscal_year": 2025,
                "confidence": 0.9,
                "verified": true,
                "verification_status": "verified",
                "source": "Annual Report",
                "company": null,
                "period": "2025",
                "quote": "Management believes liquidity remains strong",
                "value": null,
                "unit": null
              }
            ],
            "required_inputs": [],
            "input_provenance": {},
            "rule_or_model": "narrative_numeric_consistency",
            "rule_version": "64a92069682b8af5042bf05fb1d04be09c3d39b37dfbd6fd9ececf0c8a58d7bc",
            "fusion_version": "hierarchical_escalation:9776c631a261",
            "confidence": 0.9,
            "coverage": 1.0,
            "disagreement": 0.435,
            "fusion_contribution": {
              "method": "hierarchical_escalation",
              "dimension_score": 85,
              "role": "cross_modal_review"
            },
            "evidence_path_status": "VERIFIED",
            "path": [
              "document",
              "evidence_span",
              "claim",
              "consistency_check",
              "dimension",
              "fusion",
              "decision"
            ]
          }
        ],
        "verified_path_count": 2,
        "material_path_count": 17,
        "proof_coverage": 0.118,
        "initial_fusion_decision": "ABSTAIN",
        "failure_aware_decision": "ABSTAIN",
        "review_decision": "ABSTAIN"
      },
      "role_review": {
        "analyst": [
          {
            "claim": "liquidity risk signal LIQ_001",
            "risk_domain": "liquidity",
            "strength": "material",
            "evidence_path_ids": [
              "LIQ_001"
            ],
            "model": null
          },
          {
            "claim": "liquidity risk signal LIQ_003",
            "risk_domain": "liquidity",
            "strength": "material",
            "evidence_path_ids": [
              "LIQ_003"
            ],
            "model": null
          },
          {
            "claim": "liquidity risk signal LIQ_004",
            "risk_domain": "liquidity",
            "strength": "material",
            "evidence_path_ids": [
              "LIQ_004"
            ],
            "model": null
          },
          {
            "claim": "liquidity risk signal LIQ_006",
            "risk_domain": "liquidity",
            "strength": "material",
            "evidence_path_ids": [
              "LIQ_006"
            ],
            "model": null
          },
          {
            "claim": "liquidity risk signal LIQ_008",
            "risk_domain": "liquidity",
            "strength": "material",
            "evidence_path_ids": [
              "LIQ_008"
            ],
            "model": null
          },
          {
            "claim": "solvency_leverage risk signal SOL_001",
            "risk_domain": "solvency_leverage",
            "strength": "material",
            "evidence_path_ids": [
              "SOL_001"
            ],
            "model": null
          },
          {
            "claim": "solvency_leverage risk signal SOL_004",
            "risk_domain": "solvency_leverage",
            "strength": "material",
            "evidence_path_ids": [
              "SOL_004"
            ],
            "model": null
          },
          {
            "claim": "solvency_leverage risk signal SOL_006",
            "risk_domain": "solvency_leverage",
            "strength": "material",
            "evidence_path_ids": [
              "SOL_006"
            ],
            "model": null
          },
          {
            "claim": "profitability risk signal PRO_003",
            "risk_domain": "profitability",
            "strength": "material",
            "evidence_path_ids": [
              "PRO_003"
            ],
            "model": null
          },
          {
            "claim": "cash_flow risk signal CFL_004",
            "risk_domain": "cash_flow",
            "strength": "material",
            "evidence_path_ids": [
              "CFL_004"
            ],
            "model": null
          },
          {
            "claim": "cash_flow risk signal CFL_005",
            "risk_domain": "cash_flow",
            "strength": "material",
            "evidence_path_ids": [
              "CFL_005"
            ],
            "model": null
          },
          {
            "claim": "cash_flow risk signal CFL_007",
            "risk_domain": "cash_flow",
            "strength": "material",
            "evidence_path_ids": [
              "CFL_007"
            ],
            "model": null
          },
          {
            "claim": "earnings_quality risk signal EQ_001",
            "risk_domain": "earnings_quality",
            "strength": "material",
            "evidence_path_ids": [
              "EQ_001"
            ],
            "model": null
          },
          {
            "claim": "earnings_quality risk signal EQ_002",
            "risk_domain": "earnings_quality",
            "strength": "material",
            "evidence_path_ids": [
              "EQ_002"
            ],
            "model": null
          },
          {
            "claim": "earnings_quality risk signal EQ_003",
            "risk_domain": "earnings_quality",
            "strength": "material",
            "evidence_path_ids": [
              "EQ_003"
            ],
            "model": null
          },
          {
            "claim": "business_going_concern risk signal BUS_003",
            "risk_domain": "business_going_concern",
            "strength": "material",
            "evidence_path_ids": [
              "BUS_003"
            ],
            "model": null
          }
        ],
        "critic": [
          {
            "code": "UNSUPPORTED_CLAIM",
            "severity": "blocking",
            "message": "liquidity risk signal LIQ_001"
          },
          {
            "code": "UNSUPPORTED_CLAIM",
            "severity": "blocking",
            "message": "liquidity risk signal LIQ_003"
          },
          {
            "code": "UNSUPPORTED_CLAIM",
            "severity": "blocking",
            "message": "liquidity risk signal LIQ_004"
          },
          {
            "code": "UNSUPPORTED_CLAIM",
            "severity": "blocking",
            "message": "liquidity risk signal LIQ_006"
          },
          {
            "code": "UNSUPPORTED_CLAIM",
            "severity": "blocking",
            "message": "liquidity risk signal LIQ_008"
          },
          {
            "code": "UNSUPPORTED_CLAIM",
            "severity": "blocking",
            "message": "solvency_leverage risk signal SOL_001"
          },
          {
            "code": "UNSUPPORTED_CLAIM",
            "severity": "blocking",
            "message": "solvency_leverage risk signal SOL_004"
          },
          {
            "code": "UNSUPPORTED_CLAIM",
            "severity": "blocking",
            "message": "solvency_leverage risk signal SOL_006"
          },
          {
            "code": "UNSUPPORTED_CLAIM",
            "severity": "blocking",
            "message": "profitability risk signal PRO_003"
          },
          {
            "code": "UNSUPPORTED_CLAIM",
            "severity": "blocking",
            "message": "cash_flow risk signal CFL_004"
          },
          {
            "code": "UNSUPPORTED_CLAIM",
            "severity": "blocking",
            "message": "cash_flow risk signal CFL_005"
          },
          {
            "code": "UNSUPPORTED_CLAIM",
            "severity": "blocking",
            "message": "cash_flow risk signal CFL_007"
          },
          {
            "code": "UNSUPPORTED_CLAIM",
            "severity": "blocking",
            "message": "earnings_quality risk signal EQ_001"
          },
          {
            "code": "UNSUPPORTED_CLAIM",
            "severity": "blocking",
            "message": "earnings_quality risk signal EQ_002"
          },
          {
            "code": "UNSUPPORTED_CLAIM",
            "severity": "blocking",
            "message": "earnings_quality risk signal EQ_003"
          }
        ],
        "verifier": {
          "status": "REJECTED",
          "citation_errors": [
            "CFL_004",
            "CFL_005",
            "CFL_007",
            "EQ_001",
            "EQ_002",
            "EQ_003",
            "LIQ_001",
            "LIQ_003",
            "LIQ_004",
            "LIQ_006",
            "LIQ_008",
            "PRO_003",
            "SOL_001",
            "SOL_004",
            "SOL_006"
          ],
          "challenges": [
            {
              "code": "UNSUPPORTED_CLAIM",
              "severity": "blocking",
              "message": "liquidity risk signal LIQ_001"
            },
            {
              "code": "UNSUPPORTED_CLAIM",
              "severity": "blocking",
              "message": "liquidity risk signal LIQ_003"
            },
            {
              "code": "UNSUPPORTED_CLAIM",
              "severity": "blocking",
              "message": "liquidity risk signal LIQ_004"
            },
            {
              "code": "UNSUPPORTED_CLAIM",
              "severity": "blocking",
              "message": "liquidity risk signal LIQ_006"
            },
            {
              "code": "UNSUPPORTED_CLAIM",
              "severity": "blocking",
              "message": "liquidity risk signal LIQ_008"
            },
            {
              "code": "UNSUPPORTED_CLAIM",
              "severity": "blocking",
              "message": "solvency_leverage risk signal SOL_001"
            },
            {
              "code": "UNSUPPORTED_CLAIM",
              "severity": "blocking",
              "message": "solvency_leverage risk signal SOL_004"
            },
            {
              "code": "UNSUPPORTED_CLAIM",
              "severity": "blocking",
              "message": "solvency_leverage risk signal SOL_006"
            },
            {
              "code": "UNSUPPORTED_CLAIM",
              "severity": "blocking",
              "message": "profitability risk signal PRO_003"
            },
            {
              "code": "UNSUPPORTED_CLAIM",
              "severity": "blocking",
              "message": "cash_flow risk signal CFL_004"
            },
            {
              "code": "UNSUPPORTED_CLAIM",
              "severity": "blocking",
              "message": "cash_flow risk signal CFL_005"
            },
            {
              "code": "UNSUPPORTED_CLAIM",
              "severity": "blocking",
              "message": "cash_flow risk signal CFL_007"
            },
            {
              "code": "UNSUPPORTED_CLAIM",
              "severity": "blocking",
              "message": "earnings_quality risk signal EQ_001"
            },
            {
              "code": "UNSUPPORTED_CLAIM",
              "severity": "blocking",
              "message": "earnings_quality risk signal EQ_002"
            },
            {
              "code": "UNSUPPORTED_CLAIM",
              "severity": "blocking",
              "message": "earnings_quality risk signal EQ_003"
            }
          ],
          "checked_claims": 16
        },
        "recommended_decision": "REVIEW"
      },
      "epistemics": {
        "evidence_coverage": 0.045,
        "evidence_quality": 0.9,
        "model_disagreement": 0.435,
        "reliability": null,
        "calibration_status": "UNCALIBRATED",
        "probability": null
      },
      "component_telemetry": [
        {
          "component": "XBRL",
          "status": "not_executed",
          "risk_before": 0.0,
          "risk_after": 0.0,
          "delta_risk": 0.0,
          "coverage_before": 0.0,
          "coverage_after": 1.0,
          "delta_coverage": 1.0,
          "disagreement_before": 0.0,
          "disagreement_after": 0.0,
          "delta_disagreement": 0.0,
          "decision_changed": false,
          "new_evidence": 0,
          "latency_ms": 0,
          "estimated_cost_usd": 0.0
        },
        {
          "component": "rules",
          "status": "executed",
          "risk_before": 0.0,
          "risk_after": 53.8,
          "delta_risk": 53.8,
          "coverage_before": 1.0,
          "coverage_after": 1.0,
          "delta_coverage": 0.0,
          "disagreement_before": 0.0,
          "disagreement_after": 0.0,
          "delta_disagreement": 0.0,
          "decision_changed": false,
          "new_evidence": 20,
          "latency_ms": 0,
          "estimated_cost_usd": 0.0
        },
        {
          "component": "traditional_models",
          "status": "executed",
          "risk_before": 53.8,
          "risk_after": 53.8,
          "delta_risk": 0.0,
          "coverage_before": 1.0,
          "coverage_after": 1.0,
          "delta_coverage": 0.0,
          "disagreement_before": 0.0,
          "disagreement_after": 0.0,
          "delta_disagreement": 0.0,
          "decision_changed": false,
          "new_evidence": 0,
          "latency_ms": 0,
          "estimated_cost_usd": 0.0
        },
        {
          "component": "LLM_narrative",
          "status": "executed",
          "risk_before": 53.8,
          "risk_after": 53.0,
          "delta_risk": -0.8,
          "coverage_before": 1.0,
          "coverage_after": 0.045,
          "delta_coverage": -0.955,
          "disagreement_before": 0.0,
          "disagreement_after": 0.0,
          "delta_disagreement": 0.0,
          "decision_changed": false,
          "new_evidence": 2,
          "latency_ms": 0,
          "estimated_cost_usd": 0.0
        },
        {
          "component": "Critic",
          "status": "executed",
          "risk_before": 53.0,
          "risk_after": 53.0,
          "delta_risk": 0.0,
          "coverage_before": 0.045,
          "coverage_after": 0.045,
          "delta_coverage": 0.0,
          "disagreement_before": 0.0,
          "disagreement_after": 0.0,
          "delta_disagreement": 0.0,
          "decision_changed": false,
          "new_evidence": 0,
          "latency_ms": 0,
          "estimated_cost_usd": 0.0
        },
        {
          "component": "Verifier",
          "status": "executed",
          "risk_before": 53.0,
          "risk_after": 53.0,
          "delta_risk": 0.0,
          "coverage_before": 0.045,
          "coverage_after": 0.045,
          "delta_coverage": 0.0,
          "disagreement_before": 0.0,
          "disagreement_after": 0.0,
          "delta_disagreement": 0.0,
          "decision_changed": false,
          "new_evidence": 29,
          "latency_ms": 0,
          "estimated_cost_usd": 0.0
        },
        {
          "component": "fusion",
          "status": "executed",
          "risk_before": 53.0,
          "risk_after": 95.0,
          "delta_risk": 42.0,
          "coverage_before": 0.045,
          "coverage_after": 0.045,
          "delta_coverage": 0.0,
          "disagreement_before": 0.0,
          "disagreement_after": 0.435,
          "delta_disagreement": 0.435,
          "decision_changed": false,
          "new_evidence": 17,
          "latency_ms": 0,
          "estimated_cost_usd": 0.0
        }
      ]
    },
    "claim_consistency_evaluations": [
      {
        "claim": "The company may pursue refinancing during the coming year",
        "risk_dimension": "liquidity",
        "claim_target": "category_general",
        "required_evidence_types": [
          "liquidity_position",
          "cash_generation",
          "funding_pressure"
        ],
        "available_evidence_types": [
          "liquidity_position",
          "cash_generation",
          "funding_pressure"
        ],
        "missing_evidence_types": [],
        "supporting_evidence": [],
        "opposing_evidence": [
          "Cash declined by more than 10% [cash_growth=-0.3731]",
          "Operating cash flow declined by more than 10% [operating_cash_flow_growth=-0.6538]",
          "Short-term debt increased by more than 20% [short_term_debt_growth=0.7273]",
          "Current ratio is below 1.0 [current_ratio=0.8283]"
        ],
        "classification": "NOT_APPLICABLE",
        "reason_code": "CLAIM_NOT_OPTIMISTIC",
        "policy_version": "narrative-numeric-consistency-v3",
        "policy_hash": "fb4ac313d2e31033001c2794fa232cb2e69035d787df2f819fd9d104f22db905"
      },
      {
        "claim": "Management believes liquidity remains strong",
        "risk_dimension": "liquidity",
        "claim_target": "category_general",
        "required_evidence_types": [
          "liquidity_position",
          "cash_generation",
          "funding_pressure"
        ],
        "available_evidence_types": [
          "liquidity_position",
          "cash_generation",
          "funding_pressure"
        ],
        "missing_evidence_types": [],
        "supporting_evidence": [],
        "opposing_evidence": [
          "Cash declined by more than 10% [cash_growth=-0.3731]",
          "Operating cash flow declined by more than 10% [operating_cash_flow_growth=-0.6538]",
          "Short-term debt increased by more than 20% [short_term_debt_growth=0.7273]",
          "Current ratio is below 1.0 [current_ratio=0.8283]"
        ],
        "classification": "MATERIAL_CONTRADICTION",
        "reason_code": "SEVERE_VERIFIED_SIGNAL",
        "policy_version": "narrative-numeric-consistency-v3",
        "policy_hash": "fb4ac313d2e31033001c2794fa232cb2e69035d787df2f819fd9d104f22db905"
      }
    ],
    "company": "Northstar Components (Synthetic)",
    "confidence": 0.9,
    "confidence_components": {
      "core_data_completeness": 1.0,
      "numeric_provenance_coverage": 1.0,
      "verified_claim_coverage": 1.0,
      "applicable_model_coverage": 0.0,
      "temporal_depth": 1.0
    },
    "contradictions": [
      {
        "category": "liquidity",
        "management_claim": "Management believes liquidity remains strong",
        "conflicting_evidence": [
          "Cash declined by more than 10% [cash_growth=-0.3731]",
          "Operating cash flow declined by more than 10% [operating_cash_flow_growth=-0.6538]",
          "Short-term debt increased by more than 20% [short_term_debt_growth=0.7273]",
          "Current ratio is below 1.0 [current_ratio=0.8283]"
        ],
        "interpretation": "The narrative is more optimistic than the available indicators. This is a traceable consistency signal, not evidence of fraud or misstatement.",
        "evidence": {
          "document": "Annual Report",
          "page": 54,
          "source_text": "Management believes liquidity remains strong",
          "fiscal_year": 2025,
          "confidence": 0.9,
          "verified": true,
          "verification_status": "verified",
          "source": "Annual Report",
          "company": null,
          "period": "2025",
          "quote": "Management believes liquidity remains strong",
          "value": null,
          "unit": null
        }
      }
    ],
    "dimensions": {
      "liquidity": {
        "score": 85,
        "level": "Critical",
        "trend": "unknown",
        "coverage": 1.0,
        "key_drivers": [
          "LIQ_001",
          "LIQ_003",
          "LIQ_004",
          "LIQ_006",
          "LIQ_008"
        ]
      },
      "solvency_leverage": {
        "score": 63,
        "level": "High",
        "trend": "unknown",
        "coverage": 1.0,
        "key_drivers": [
          "SOL_004",
          "SOL_001",
          "SOL_006"
        ]
      },
      "profitability": {
        "score": 20,
        "level": "Low",
        "trend": "unknown",
        "coverage": 1.0,
        "key_drivers": [
          "PRO_003"
        ]
      },
      "cash_flow": {
        "score": 45,
        "level": "Moderate",
        "trend": "unknown",
        "coverage": 1.0,
        "key_drivers": [
          "CFL_005",
          "CFL_004",
          "CFL_007"
        ]
      },
      "earnings_quality": {
        "score": 56,
        "level": "Moderate",
        "trend": "unknown",
        "coverage": 1.0,
        "key_drivers": [
          "EQ_001",
          "EQ_002",
          "EQ_003"
        ]
      },
      "accounting": {
        "score": null,
        "level": "N/A",
        "trend": "unknown",
        "coverage": 0.0,
        "key_drivers": []
      },
      "governance_audit": {
        "score": null,
        "level": "N/A",
        "trend": "unknown",
        "coverage": 0.0,
        "key_drivers": []
      },
      "business_going_concern": {
        "score": 28,
        "level": "Low",
        "trend": "unknown",
        "coverage": 1.0,
        "key_drivers": [
          "BUS_003"
        ]
      }
    },
    "disclaimer": "Risk scores are heuristic assessment scores, not bankruptcy probabilities or investment advice.",
    "disclosure_tensions": [
      {
        "claim": "The company may pursue refinancing during the coming year",
        "supporting_evidence": [],
        "opposing_evidence": [
          "Cash declined by more than 10% [cash_growth=-0.3731]",
          "Operating cash flow declined by more than 10% [operating_cash_flow_growth=-0.6538]",
          "Short-term debt increased by more than 20% [short_term_debt_growth=0.7273]",
          "Current ratio is below 1.0 [current_ratio=0.8283]"
        ],
        "context": "Compared with all available normalized evidence for the claim category.",
        "classification": "Material Contradiction",
        "confidence": 0.9,
        "source": {
          "document": "Annual Report",
          "page": 54,
          "source_text": "The company may pursue refinancing during the coming year",
          "fiscal_year": 2025,
          "confidence": 0.9,
          "verified": true,
          "verification_status": "verified",
          "source": "Annual Report",
          "company": null,
          "period": "2025",
          "quote": "The company may pursue refinancing during the coming year",
          "value": null,
          "unit": null
        },
        "reason_code": "CLAIM_NOT_OPTIMISTIC",
        "evidence_sufficiency": "complete"
      },
      {
        "claim": "Management believes liquidity remains strong",
        "supporting_evidence": [],
        "opposing_evidence": [
          "Cash declined by more than 10% [cash_growth=-0.3731]",
          "Operating cash flow declined by more than 10% [operating_cash_flow_growth=-0.6538]",
          "Short-term debt increased by more than 20% [short_term_debt_growth=0.7273]",
          "Current ratio is below 1.0 [current_ratio=0.8283]"
        ],
        "context": "Compared with all available normalized evidence for the claim category.",
        "classification": "Material Contradiction",
        "confidence": 0.9,
        "source": {
          "document": "Annual Report",
          "page": 54,
          "source_text": "Management believes liquidity remains strong",
          "fiscal_year": 2025,
          "confidence": 0.9,
          "verified": true,
          "verification_status": "verified",
          "source": "Annual Report",
          "company": null,
          "period": "2025",
          "quote": "Management believes liquidity remains strong",
          "value": null,
          "unit": null
        },
        "reason_code": "SEVERE_VERIFIED_SIGNAL",
        "evidence_sufficiency": "complete"
      }
    ],
    "enterprise_fusion": {
      "method": "hierarchical_escalation",
      "severity": "critical",
      "score": 95.0,
      "decision": "ABSTAIN",
      "evidence_coverage": 0.045,
      "decision_confidence": 0.9,
      "disagreement": 0.435,
      "drivers": [
        "liquidity"
      ],
      "rationale": "Coverage-aware non-compensatory fusion; the highest supported dimension is a monotonic floor and missing dimensions are excluded",
      "evidence_quality": 0.9,
      "reliability": null,
      "reliability_status": "UNCALIBRATED",
      "reason_codes": [
        "INSUFFICIENT_EVIDENCE",
        "CRITICAL_DIMENSION_ESCALATION",
        "UNVALIDATED_RELIABILITY"
      ]
    },
    "evidence_coverage": 0.045,
    "evidence_quality": 0.9,
    "failure_state": {
      "decision": "ABSTAIN",
      "degraded": true,
      "blocking_failures": [],
      "review_failures": [
        "conflicting_evidence"
      ]
    },
    "final_decision": "ABSTAIN",
    "legacy_weighted_score": 53.0,
    "missing_information": [
      "free_cash_flow_growth: N/A — Denominator is zero. Impact: assessment confidence reduced."
    ],
    "models": [
      {
        "name": "Altman Z-Score",
        "output": null,
        "interpretation": "Insufficient data",
        "applicability": "LIMITED: missing 1 required component(s)",
        "inputs": {
          "cash": 42,
          "accounts_receivable": 180,
          "inventory": 140,
          "current_assets": 410,
          "total_assets": 1200,
          "accounts_payable": 155,
          "current_liabilities": 495,
          "short_term_debt": 190,
          "long_term_debt": 410,
          "total_debt": 600,
          "total_liabilities": 910,
          "shareholder_equity": 290,
          "retained_earnings": 80,
          "revenue": 1350,
          "gross_profit": 310,
          "operating_income": 68,
          "ebit": 68,
          "ebitda": 115,
          "interest_expense": 55,
          "net_income": 32,
          "operating_cash_flow": 18,
          "capital_expenditure": 75,
          "working_capital": -85
        },
        "formula": "1.2X1+1.4X2+3.3X3+0.6X4+1.0X5",
        "missing_components": [
          "market_value_equity"
        ],
        "derived_outputs": {}
      },
      {
        "name": "Beneish M-Score",
        "output": null,
        "interpretation": "Insufficient data",
        "applicability": "LIMITED: missing 3 required component(s)",
        "inputs": {},
        "formula": "-4.84+0.920DSRI+0.528GMI+0.404AQI+0.892SGI+0.115DEPI-0.172SGAI+4.679TATA-0.327LVGI",
        "missing_components": [
          "depreciation",
          "ppe",
          "sga"
        ],
        "derived_outputs": {}
      },
      {
        "name": "Piotroski F-Score",
        "output": null,
        "interpretation": "Insufficient data",
        "applicability": "LIMITED: Piotroski-style proxy uses end-of-period asset denominators; missing 1 required component(s)",
        "inputs": {},
        "formula": "Nine proxy binary signals (0-9)",
        "missing_components": [
          "shares_outstanding"
        ],
        "derived_outputs": {}
      },
      {
        "name": "Ohlson O-Score",
        "output": null,
        "interpretation": "Insufficient data",
        "applicability": "LIMITED: missing 3 required component(s)",
        "inputs": {
          "cash": 42,
          "accounts_receivable": 180,
          "inventory": 140,
          "current_assets": 410,
          "total_assets": 1200,
          "accounts_payable": 155,
          "current_liabilities": 495,
          "short_term_debt": 190,
          "long_term_debt": 410,
          "total_debt": 600,
          "total_liabilities": 910,
          "shareholder_equity": 290,
          "retained_earnings": 80,
          "revenue": 1350,
          "gross_profit": 310,
          "operating_income": 68,
          "ebit": 68,
          "ebitda": 115,
          "interest_expense": 55,
          "net_income": 32,
          "operating_cash_flow": 18,
          "capital_expenditure": 75,
          "working_capital": -85
        },
        "formula": "Ohlson (1980) nine-factor logit",
        "missing_components": [
          "funds_from_operations",
          "gnp_price_index",
          "prior_net_income"
        ],
        "derived_outputs": {}
      }
    ],
    "overall_score": 95.0,
    "reliability_status": "UNCALIBRATED",
    "reporting_period": "2025",
    "risk_level": "Critical",
    "triggered_rules": [
      {
        "rule_id": "LIQ_001",
        "category": "liquidity",
        "severity": "high",
        "score_delta": 18,
        "rationale": "Current assets do not cover current liabilities.",
        "evidence": [
          "current_ratio=0.8282828282828283 < 1.0"
        ],
        "source_refs": [],
        "family": "liquidity_coverage",
        "required_inputs": [
          "current_ratio"
        ],
        "input_provenance": {
          "current_ratio": []
        }
      },
      {
        "rule_id": "LIQ_002",
        "category": "liquidity",
        "severity": "medium",
        "score_delta": 9,
        "rationale": "Liquidity cushion is thin.",
        "evidence": [
          "current_ratio=0.8282828282828283 < 1.25"
        ],
        "source_refs": [],
        "family": "liquidity_coverage",
        "required_inputs": [
          "current_ratio"
        ],
        "input_provenance": {
          "current_ratio": []
        }
      },
      {
        "rule_id": "LIQ_003",
        "category": "liquidity",
        "severity": "high",
        "score_delta": 14,
        "rationale": "Liquid assets provide weak short-term coverage.",
        "evidence": [
          "quick_ratio=0.5454545454545454 < 0.75"
        ],
        "source_refs": [],
        "family": null,
        "required_inputs": [
          "quick_ratio"
        ],
        "input_provenance": {
          "quick_ratio": []
        }
      },
      {
        "rule_id": "LIQ_004",
        "category": "liquidity",
        "severity": "medium",
        "score_delta": 8,
        "rationale": "Immediate cash coverage is limited.",
        "evidence": [
          "cash_ratio=0.08484848484848485 < 0.15"
        ],
        "source_refs": [],
        "family": null,
        "required_inputs": [
          "cash_ratio"
        ],
        "input_provenance": {
          "cash_ratio": []
        }
      },
      {
        "rule_id": "LIQ_005",
        "category": "liquidity",
        "severity": "high",
        "score_delta": 16,
        "rationale": "Negative working capital increases short-term funding pressure.",
        "evidence": [
          "working_capital=-85 < 0"
        ],
        "source_refs": [],
        "family": "liquidity_coverage",
        "required_inputs": [
          "working_capital"
        ],
        "input_provenance": {
          "working_capital": []
        }
      },
      {
        "rule_id": "LIQ_006",
        "category": "liquidity",
        "severity": "medium",
        "score_delta": 10,
        "rationale": "Cash declined materially year over year.",
        "evidence": [
          "cash_growth=-0.373134328358209 < -0.2"
        ],
        "source_refs": [],
        "family": null,
        "required_inputs": [
          "cash_growth"
        ],
        "input_provenance": {
          "cash_growth": []
        }
      },
      {
        "rule_id": "LIQ_007",
        "category": "liquidity",
        "severity": "high",
        "score_delta": 18,
        "rationale": "Deteriorating liquidity combines with rising refinancing pressure.",
        "evidence": [
          "current_ratio=0.8282828282828283 < 1.0",
          "short_term_debt_growth=0.7272727272727273 > 0.2",
          "cash_growth=-0.373134328358209 < 0"
        ],
        "source_refs": [],
        "family": "liquidity_coverage",
        "required_inputs": [
          "current_ratio",
          "short_term_debt_growth",
          "cash_growth"
        ],
        "input_provenance": {
          "current_ratio": [],
          "short_term_debt_growth": [],
          "cash_growth": []
        }
      },
      {
        "rule_id": "LIQ_008",
        "category": "liquidity",
        "severity": "high",
        "score_delta": 15,
        "rationale": "Both cash reserves and operating cash generation weakened.",
        "evidence": [
          "cash_growth=-0.373134328358209 < -0.25",
          "operating_cash_flow_growth=-0.6538461538461539 < -0.2"
        ],
        "source_refs": [],
        "family": null,
        "required_inputs": [
          "cash_growth",
          "operating_cash_flow_growth"
        ],
        "input_provenance": {
          "cash_growth": [],
          "operating_cash_flow_growth": []
        }
      },
      {
        "rule_id": "SOL_001",
        "category": "solvency_leverage",
        "severity": "high",
        "score_delta": 17,
        "rationale": "Debt is high relative to book equity.",
        "evidence": [
          "debt_to_equity=2.0689655172413794 > 2.0"
        ],
        "source_refs": [],
        "family": null,
        "required_inputs": [
          "debt_to_equity"
        ],
        "input_provenance": {
          "debt_to_equity": []
        }
      },
      {
        "rule_id": "SOL_004",
        "category": "solvency_leverage",
        "severity": "high",
        "score_delta": 18,
        "rationale": "Operating earnings weakly cover interest expense.",
        "evidence": [
          "interest_coverage=1.2363636363636363 < 1.5"
        ],
        "source_refs": [],
        "family": "interest_coverage",
        "required_inputs": [
          "interest_coverage"
        ],
        "input_provenance": {
          "interest_coverage": []
        }
      },
      {
        "rule_id": "SOL_005",
        "category": "solvency_leverage",
        "severity": "medium",
        "score_delta": 9,
        "rationale": "Interest coverage has limited headroom.",
        "evidence": [
          "interest_coverage=1.2363636363636363 < 3.0"
        ],
        "source_refs": [],
        "family": "interest_coverage",
        "required_inputs": [
          "interest_coverage"
        ],
        "input_provenance": {
          "interest_coverage": []
        }
      },
      {
        "rule_id": "SOL_006",
        "category": "solvency_leverage",
        "severity": "high",
        "score_delta": 18,
        "rationale": "Debt burden is high relative to EBITDA.",
        "evidence": [
          "debt_to_ebitda=5.217391304347826 > 5.0"
        ],
        "source_refs": [],
        "family": null,
        "required_inputs": [
          "debt_to_ebitda"
        ],
        "input_provenance": {
          "debt_to_ebitda": []
        }
      },
      {
        "rule_id": "PRO_003",
        "category": "profitability",
        "severity": "medium",
        "score_delta": 10,
        "rationale": "Gross margin contracted materially.",
        "evidence": [
          "gross_margin_change=-0.03037037037037038 < -0.03"
        ],
        "source_refs": [],
        "family": null,
        "required_inputs": [
          "gross_margin_change"
        ],
        "input_provenance": {
          "gross_margin_change": []
        }
      },
      {
        "rule_id": "CFL_002",
        "category": "cash_flow",
        "severity": "high",
        "score_delta": 14,
        "rationale": "Free cash flow is negative.",
        "evidence": [
          "free_cash_flow=-57 < 0"
        ],
        "source_refs": [],
        "family": "cash_deficit",
        "required_inputs": [
          "free_cash_flow"
        ],
        "input_provenance": {
          "free_cash_flow": []
        }
      },
      {
        "rule_id": "CFL_004",
        "category": "cash_flow",
        "severity": "medium",
        "score_delta": 10,
        "rationale": "Operating cash flow declined rapidly.",
        "evidence": [
          "operating_cash_flow_growth=-0.6538461538461539 < -0.25"
        ],
        "source_refs": [],
        "family": null,
        "required_inputs": [
          "operating_cash_flow_growth"
        ],
        "input_provenance": {
          "operating_cash_flow_growth": []
        }
      },
      {
        "rule_id": "CFL_005",
        "category": "cash_flow",
        "severity": "high",
        "score_delta": 15,
        "rationale": "Positive earnings have not converted into free cash flow.",
        "evidence": [
          "net_income=32 > 0",
          "free_cash_flow=-57 < 0"
        ],
        "source_refs": [],
        "family": "cash_deficit",
        "required_inputs": [
          "net_income",
          "free_cash_flow"
        ],
        "input_provenance": {
          "net_income": [],
          "free_cash_flow": []
        }
      },
      {
        "rule_id": "CFL_007",
        "category": "cash_flow",
        "severity": "medium",
        "score_delta": 10,
        "rationale": "Cash conversion from reported earnings is weak.",
        "evidence": [
          "cfo_to_net_income=0.5625 < 0.8"
        ],
        "source_refs": [],
        "family": null,
        "required_inputs": [
          "cfo_to_net_income"
        ],
        "input_provenance": {
          "cfo_to_net_income": []
        }
      },
      {
        "rule_id": "EQ_001",
        "category": "earnings_quality",
        "severity": "high",
        "score_delta": 17,
        "rationale": "Revenue and earnings rose while operating cash flow fell.",
        "evidence": [
          "revenue_growth=0.08 > 0",
          "net_income_growth=0.14285714285714285 > 0",
          "operating_cash_flow_growth=-0.6538461538461539 < 0"
        ],
        "source_refs": [],
        "family": null,
        "required_inputs": [
          "revenue_growth",
          "net_income_growth",
          "operating_cash_flow_growth"
        ],
        "input_provenance": {
          "revenue_growth": [],
          "net_income_growth": [],
          "operating_cash_flow_growth": []
        }
      },
      {
        "rule_id": "EQ_002",
        "category": "earnings_quality",
        "severity": "high",
        "score_delta": 16,
        "rationale": "Receivables growth substantially outpaces revenue growth.",
        "evidence": [
          "accounts_receivable_growth=0.44 > 0.25",
          "revenue_growth=0.08 < 0.1"
        ],
        "source_refs": [],
        "family": null,
        "required_inputs": [
          "accounts_receivable_growth",
          "revenue_growth"
        ],
        "input_provenance": {
          "accounts_receivable_growth": [],
          "revenue_growth": []
        }
      },
      {
        "rule_id": "EQ_003",
        "category": "earnings_quality",
        "severity": "medium",
        "score_delta": 13,
        "rationale": "Inventory growth outpaces sales and may indicate slowing demand.",
        "evidence": [
          "inventory_growth=0.3333333333333333 > 0.25",
          "revenue_growth=0.08 < 0.1"
        ],
        "source_refs": [],
        "family": null,
        "required_inputs": [
          "inventory_growth",
          "revenue_growth"
        ],
        "input_provenance": {
          "inventory_growth": [],
          "revenue_growth": []
        }
      },
      {
        "rule_id": "BUS_003",
        "category": "business_going_concern",
        "severity": "high",
        "score_delta": 18,
        "rationale": "Operations depend materially on successful refinancing.",
        "evidence": [
          "refinancing_dependency=True == True"
        ],
        "source_refs": [
          {
            "document": "Annual Report",
            "page": 54,
            "source_text": "The company may pursue refinancing during the coming year",
            "fiscal_year": 2025,
            "confidence": 0.9,
            "verified": true,
            "verification_status": "verified",
            "source": "Annual Report",
            "company": null,
            "period": "2025",
            "quote": "The company may pursue refinancing during the coming year",
            "value": null,
            "unit": null
          }
        ],
        "family": null,
        "required_inputs": [
          "refinancing_dependency"
        ],
        "input_provenance": {
          "refinancing_dependency": [
            {
              "document": "Annual Report",
              "page": 54,
              "source_text": "The company may pursue refinancing during the coming year",
              "fiscal_year": 2025,
              "confidence": 0.9,
              "verified": true,
              "verification_status": "verified",
              "source": "Annual Report",
              "company": null,
              "period": "2025",
              "quote": "The company may pursue refinancing during the coming year",
              "value": null,
              "unit": null
            }
          ]
        }
      }
    ]
  }
} as DemoFixture;
